### ISSUE TITLE
car_workspace.json can no longer be imported to Conversation service

### ISSUE THREAD

**Issue by danrohtbart** [watson-developer-cloud/conversation-simple#100]
Please look into recent update(s) to car_workspace.json. Previous versions could be imported into Watson Conversation service using [your instructions](https://github.com/watson-developer-cloud/conversation-simple?cm_mc_uid=41548878224914893412698&cm_mc_sid_50200000=#import-a-workspace), but the new version cannot. Thanks, Dan

**Comment by germanattanasio** [comment]
@stevenpkg can you look at this?

**Comment by Oliver-I** [comment]
@danrohtbart Hi Dan, do you receive an error when you try to import the JSON file? If you do, can you let me know what error message you're seeing?

**Comment by tommysusanto** [comment]
Bump +1, getting the same error too. It says " Unable to import workspace from file car_workspace.json. Error: Unable to parse input. Please ensure the uploaded file is valid JSON."

**Comment by stevenpkg** [comment]
Are you downloading the project as zip file and get the car_workspace.json from there?

**Comment by danrohtbart** [comment]
Thanks for confirming @tommysusanto . @stevenpkg I did Save As from https://raw.githubusercontent.com/watson-developer-cloud/conversation-simple/master/training/car_workspace.json.

**Comment by ojikobeshi** [comment]
Any update posted concern? I am also experiencing the same issue. Can't import from master branch. The version of JSON file that works though is the one from commit 282b2c75607cd508cdedaa3ce82523a447e86e99

**Comment by stevenpkg** [comment]
You need to download the project as a zip file and extract the car_workspace.json If you save the car_workspace.json directly it seem to get unwanted characters in it, and gives errors

**Comment by abideandride** [comment]
I tried that (and cloning). I receive the same errors as the others.

**Comment by stevenpkg** [comment]
Okay I can confirm the problem. Please use the version in commit https://github.com/watson-developer-cloud/conversation-simple/commit/282b2c75607cd508cdedaa3ce82523a447e86e99 for now, hopefully I will have a solution soon.

**Comment by stevenpkg** [comment]
This should be fixed now, please let me know if you can now import okay

**Comment by abideandride** [comment]
Unfortunately, I'm still getting the same error. I downloaded the zip file and extracted the new file.

**Comment by stevenpkg** [comment]
@abideandride can you try this workspace

[car_workspace-no-formating.json.zip](https://github.com/watson-developer-cloud/conversation-simple/files/866485/car_workspace-no-formating.json.zip)

**Comment by abideandride** [comment]
@stevenpkg That worked! Thanks!

**Comment by stevenpkg** [comment]
Strange, the same file uploaded, but when you downloaded it, it didn't work. Can you check the json workspace you tried before in http://jsonviewer.stack.hu/ see if its valid and remove formatting, and try it again

**Comment by abideandride** [comment]
That worked. I didn't think about removing the whitespace. I did verify it was proper JSON in a different editor.

**Comment by stevenpkg** [comment]
Thanks @abideandride so I am not sure why the workspace is getting some funny formatting problems, but the answer is to clean the formatting in some online JSON validator. I am going to add a ziped version of the workspace that hopefully fixes the problem

**Comment by tommysusanto** [comment]
@stevenpkg Thanks. The no formatting works

**Comment by danrohtbart** [comment]
You all are awesome. Thanks for helping! The zip file works, but downloading even the new JSON file doesn't work for me. Once I run it through the validator at http://jsoneditoronline.org/ and save, it works. _I'm OK closing this as a known issue if you all are_

**Comment by danrohtbart** [comment]
Confirmed that the changes @adamkingit made successfully fixed the problem for me, with no need to pass through a validator.

**Comment by germanattanasio** [comment]
As you can see this is still happening (see #103)

**Comment by kmohanarangam** [comment]
@stevenpkg  your fork works. However the one under https://github.com/watson-developer-cloud/conversation-simple is incorrect. Looks like merge didn't happen correctly. 

I used your fork. Thanks for the quick response.
